### ISSUE TITLE
EarlyLoadingChecker warning

### ISSUE THREAD

**Issue by DustScripts** [Sindusk/wyvernmods#1]
Sindusk,
Hi, I am helping friends setup a private server and while loading in the Halloween mod from bdew we recieved the below (bottom of post.)  I reached out to bdew on his git and this is the response.  

Response from bdew.
WARNING org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod WyvernMods loaded server class com.wurmonline.server.players.Titles$Title during phase init

This line means that mod has loaded said class too early and no other mod will be able to modify it, this needs to be fixed in Wyvern Mods

The other error i'm not really sure what's that about, i already changed the method how titles are registered for next update - which will be out in the next week or two and might or might not fix it... but with the previous warning it still won't work unless wyvern mods is fixed.

From Logs:

`
[12:59:29 AM] INFO mod.sin.wyvern.PlayerTitles: Created new title with ID #10002: ["Pastamancer", "Pastamancer"]
[12:59:29 AM] INFO mod.sin.wyvern.PlayerTitles: Created new title with ID #20009: ["The Crazy Cat Lord", "The Crazy Cat Lady"]
[12:59:29 AM] INFO mod.sin.wyvern.PlayerTitles: Created new title with ID #10000: ["Titanslayer", "Titanslayer"]
[12:59:29 AM] INFO mod.sin.wyvern.PlayerTitles: Created new title with ID #10001: ["Spectral", "Spectral"]
[12:59:29 AM] WARNING org.gotti.wurmunlimited.modloader.EarlyLoadingChecker: Mod WyvernMods loaded server class com.wurmonline.server.players.Titles$Title during phase init
[12:59:29 AM] SEVERE org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher: Invalid pc in LineNumberTable in class file com/wurmonline/server/players/Titles$Title
java.lang.ClassFormatError: Invalid pc in LineNumberTable in class file com/wurmonline/server/players/Titles$Title
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
at javassist.Loader.findClass(Loader.java:377)
at org.gotti.wurmunlimited.modloader.classhooks.HookManager$1.findClass(HookManager.java:155)
at javassist.Loader.loadClass(Loader.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at mod.sin.wyvern.PlayerTitles.init(PlayerTitles.java:36)
at mod.sin.wyvern.WyvernMods.init(WyvernMods.java:1371)
at org.gotti.wurmunlimited.modloader.ModLoaderShared.lambda$loadModsFromModDir$8(ModLoaderShared.java:174)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at org.gotti.wurmunlimited.modloader.ModLoaderShared.loadModsFromModDir(ModLoaderShared.java:172)
at org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher.main(DelegatedLauncher.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at javassist.Loader.run(Loader.java:286)
at org.gotti.wurmunlimited.serverlauncher.ServerLauncher.main(ServerLauncher.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at PatchedLauncher.main(PatchedLauncher.java:20)
`

**Comment by DustScripts** [comment]
Some FYI, we turned off custom titles and was able to bring it up.  So this should help pinpoint where to look at
